[op]
GITHUB_TOKEN = "op://Private/GitHub Token/token"
ANTHROPIC_API_KEY = "op://Private/Anthropic/credential"
OPENAI_API_KEY = "op://Private/OpenAI/api_key"
CONTEXT7_API_KEY = "op://Private/Context7/api_key"
EXA_API_KEY = "op://Private/Exa/api_key"
